// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ms7riy_zKqFpoZ8t9sKl1zp2SZVygPI',
    appId: '1:178016124325:web:d29c3114bff62640453c4c',
    messagingSenderId: '178016124325',
    projectId: 'agrodoctor-358507',
    authDomain: 'agrodoctor-358507.firebaseapp.com',
    storageBucket: 'agrodoctor-358507.appspot.com',
    measurementId: 'G-7VENHYZ3TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVXbkzEHDtWUC2pquu88p1rf7iXX8oRaA',
    appId: '1:178016124325:android:514a64ff2fb7edbd453c4c',
    messagingSenderId: '178016124325',
    projectId: 'agrodoctor-358507',
    storageBucket: 'agrodoctor-358507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsE9WGlUWv8d7zWqY7_Vx1q_2d4tG_v7U',
    appId: '1:178016124325:ios:7574183e6aa35233453c4c',
    messagingSenderId: '178016124325',
    projectId: 'agrodoctor-358507',
    storageBucket: 'agrodoctor-358507.appspot.com',
    iosClientId: '178016124325-m2v89hsvda80nq0q9d0a7ut3gnmhd9q4.apps.googleusercontent.com',
    iosBundleId: 'com.fouren.agroSpmManager',
  );
}
